// This file was auto-generated by `tool/generate_test_entrypoints.dart`.
// ignore_for_file: avoid_print
import 'package:flutter_test/flutter_test.dart';

import 'download_stroke_order_test.dart' as download_stroke_order_test;
import 'stroke_order_animation_controller_test.dart'
    as stroke_order_animation_controller_test;
import 'stroke_order_animator_test.dart' as stroke_order_animator_test;
import 'stroke_order_test.dart' as stroke_order_test;

void main() {
  group(
    'download_stroke_order_test.dart: ',
    download_stroke_order_test.main,
  );
  group(
    'stroke_order_animation_controller_test.dart: ',
    stroke_order_animation_controller_test.main,
  );
  group(
    'stroke_order_animator_test.dart: ',
    stroke_order_animator_test.main,
  );
  group(
    'stroke_order_test.dart: ',
    stroke_order_test.main,
  );
}
