name: Auto-Approve

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: |
      (
        github.event_name == 'issue_comment'
        && github.event.issue.pull_request != ''
        && github.event.comment.user.login == 'Mr-Pepe'
        && contains(github.event.comment.body, 'LGTM')
      ) || (
        github.event_name == 'pull_request_review'
        && github.event.review.user.login == 'Mr-Pepe'
        && github.event.review.body == 'LGTM'
      )
    permissions:
      pull-requests: write
    steps:
    - name: Approve PR
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'APPROVE'
          })
