# Builds the documentation and fails the build for some warnings.
# This workflow is only run once per week because building the documentation takes a long time.

name: Check docs

on:
  schedule:
    - cron: "0 0 * * 0" # Run on Sundays

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install just
        run: sudo snap install --edge --classic just

      - name: Build and check docs
        run: |
          just get-dependencies
          dart doc
